using System;
using System.Runtime.Serialization;

namespace com.etak.core.model
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[DataContract]
	[Serializable]
	public class ImeiAssnHist
	{
		#region Private Members
		 
		private int _resourceid; 
		private string _imei;
		private DateTime? _startdate;
		private DateTime? _enddate;
		#endregion
		
		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual int Resourceid
		{
			get { return _resourceid; }
			set { _resourceid = value; }
		}


		public virtual string Imei
		{
			get { return _imei; }
			set { _imei = value; }
		}
			
		/// <summary>
		/// 
		/// </summary>		
		public virtual DateTime? StartDate
		{
			get { return _startdate; }
			set { _startdate = value; }
		}

		
		public virtual DateTime? EndDate
		{
			get { return _enddate; }
			set { _enddate = value; }
		}

		#endregion Public Properties

		/// <summary>
		/// Override Equals method needed by Nhibernate to map the entity 
		/// </summary>
		/// <param name="obj"></param>
		/// <returns></returns>
		public override bool Equals(object obj)
		{
			if (this == obj) return true;

			var other = obj as ImeiAssnHist;
			if (other == null) return false;

			if (StartDate == other.StartDate && Resourceid == other.Resourceid) 
				return true;

			return false;
		}

		/// <summary>
		/// Override GetHashCode method needed by Nhibernate to map the entity
		/// </summary>
		/// <returns></returns>
		public override int GetHashCode()
		{
		    unchecked
		    {
		        int result = StartDate.GetHashCode();
		        result = 29*result + Resourceid.GetHashCode();

		        return result;
		    }
		}
	}
}
