//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Text;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using com.etak.core.bizops.SOAPExtensions;

namespace com.etak.core.bizops.revenue.ChargeService.Proxy
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [WebServiceBinding(Name = "IApplyRecurringChargeSoapBinding", Namespace = "http://webservice.etak.com/")]
    public partial class IApplyRecurringCharge : System.Web.Services.Protocols.SoapHttpClientProtocol, IApplyRecurringChargeInterface
    {

        private System.Threading.SendOrPostCallback firstPeriodChargingApplyOperationCompleted;

        /// <remarks/>
        public IApplyRecurringCharge()
        {
            this.Url = "http://192.168.18.11:8080/chargeapi/services/ApplyRecurringCharge";
        }

        /// <remarks/>
        public event firstPeriodChargingApplyCompletedEventHandler firstPeriodChargingApplyCompleted;

        /// <remarks/>
        /// 
        /// 
        /// 
        [SoapDocumentMethod("", RequestNamespace = "http://apis.etak.com/", ResponseNamespace = "http://apis.etak.com/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        // MANUALLY ADDED
        [TraceExtension]
        [return: XmlElement("return", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public chargingApplyResponse firstPeriodChargingApply([XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)] chargingRequestParameters chargingRequestParameters)
        {
            object[] results = this.Invoke("firstPeriodChargingApply", new object[] {
                    chargingRequestParameters});
            return ((chargingApplyResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginfirstPeriodChargingApply(chargingRequestParameters chargingRequestParameters, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("firstPeriodChargingApply", new object[] {
                    chargingRequestParameters}, callback, asyncState);
        }

        /// <remarks/>
        public chargingApplyResponse EndfirstPeriodChargingApply(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((chargingApplyResponse)(results[0]));
        }

        /// <remarks/>
        public void firstPeriodChargingApplyAsync(chargingRequestParameters chargingRequestParameters)
        {
            this.firstPeriodChargingApplyAsync(chargingRequestParameters, null);
        }

        /// <remarks/>
        public void firstPeriodChargingApplyAsync(chargingRequestParameters chargingRequestParameters, object userState)
        {
            if ((this.firstPeriodChargingApplyOperationCompleted == null))
            {
                this.firstPeriodChargingApplyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfirstPeriodChargingApplyOperationCompleted);
            }
            this.InvokeAsync("firstPeriodChargingApply", new object[] {
                    chargingRequestParameters}, this.firstPeriodChargingApplyOperationCompleted, userState);
        }

        private void OnfirstPeriodChargingApplyOperationCompleted(object arg)
        {
            if ((this.firstPeriodChargingApplyCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.firstPeriodChargingApplyCompleted(this, new firstPeriodChargingApplyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://apis.etak.com/")]
    public partial class chargingRequestParameters
    {

        private long accountIdField;

        private System.DateTime? chargeDateField;

        private bool chargeDateFieldSpecified;

        private int chargeIdField;

        private long customerChargeScheduleIdField;

        private int customerIdField;

        private long customerProductIdField;

        private int cycleNumberField;

        private System.DateTime? endDateField;

        private bool endDateFieldSpecified;

        private int periodNumberField;

        private System.DateTime? priceEffectiveDateField;

        private bool priceEffectiveDateFieldSpecified;

        private System.DateTime startDateField;

        private bool startDateFieldSpecified;

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long accountId
        {
            get
            {
                return this.accountIdField;
            }
            set
            {
                this.accountIdField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime? chargeDate
        {
            get
            {
                return this.chargeDateField;
            }
            set
            {
                this.chargeDateField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool chargeDateSpecified
        {
            get
            {
                return this.chargeDateFieldSpecified;
            }
            set
            {
                this.chargeDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int chargeId
        {
            get
            {
                return this.chargeIdField;
            }
            set
            {
                this.chargeIdField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long customerChargeScheduleId
        {
            get
            {
                return this.customerChargeScheduleIdField;
            }
            set
            {
                this.customerChargeScheduleIdField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int customerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long customerProductId
        {
            get
            {
                return this.customerProductIdField;
            }
            set
            {
                this.customerProductIdField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cycleNumber
        {
            get
            {
                return this.cycleNumberField;
            }
            set
            {
                this.cycleNumberField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime? endDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool endDateSpecified
        {
            get
            {
                return this.endDateFieldSpecified;
            }
            set
            {
                this.endDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int periodNumber
        {
            get
            {
                return this.periodNumberField;
            }
            set
            {
                this.periodNumberField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime? priceEffectiveDate
        {
            get
            {
                return this.priceEffectiveDateField;
            }
            set
            {
                this.priceEffectiveDateField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool priceEffectiveDateSpecified
        {
            get
            {
                return this.priceEffectiveDateFieldSpecified;
            }
            set
            {
                this.priceEffectiveDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime startDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool startDateSpecified
        {
            get
            {
                return this.startDateFieldSpecified;
            }
            set
            {
                this.startDateFieldSpecified = value;
            }
        }


        /// <summary>
        /// ToString
        /// </summary>
        /// <returns></returns>
        public override string ToString()
        {
            StringBuilder str = new StringBuilder();
            try
            {
                str.AppendLineFormat("accountIdField:{0}", accountIdField.ToString());
                str.AppendLineFormat("chargeDateField:{0}", chargeDateField == null ? "" : chargeDateField.ToString());
                str.AppendLineFormat("chargeDateFieldSpecified:{0}", chargeDateFieldSpecified.ToString());
                str.AppendLineFormat("chargeIdField:{0}", chargeIdField.ToString());
                str.AppendLineFormat("customerChargeScheduleIdField:{0}", customerChargeScheduleIdField.ToString());
                str.AppendLineFormat("customerIdField:{0}", customerIdField.ToString());
                str.AppendLineFormat("customerProductIdField:{0}", customerProductIdField.ToString());
                str.AppendLineFormat("cycleNumberField:{0}", cycleNumberField.ToString());
                str.AppendLineFormat("endDateField:{0}", endDateField == null ? "" : endDateField.ToString());
                str.AppendLineFormat("endDateFieldSpecified:{0}", endDateFieldSpecified.ToString());
                str.AppendLineFormat("periodNumberField:{0}", periodNumberField.ToString());
                str.AppendLineFormat("priceEffectiveDateField:{0}", priceEffectiveDateField == null ? "" : priceEffectiveDateField.ToString());
                str.AppendLineFormat("priceEffectiveDateFieldSpecified:{0}", priceEffectiveDateFieldSpecified.ToString());
                str.AppendLineFormat("startDateField:{0}", startDateField.ToString());
                str.AppendLineFormat("startDateFieldSpecified:{0}", startDateFieldSpecified.ToString());
            }
            catch { }
            return str. ToString();
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://apis.etak.com/")]
    public partial class nextChargeScheduleInfo
    {

        private long accountIdField;

        private int chargeIdField;

        private System.DateTime createDateField;

        private bool createDateFieldSpecified;

        private int currentCycleNumberField;

        private long customerChargeScheduleIdField;

        private int customerIdField;

        private long customerProductIdField;

        private System.DateTime nextChargeDateField;

        private bool nextChargeDateFieldSpecified;

        private int nextPeriodNumberField;

        private System.DateTime priceEffectiveDateField;

        private bool priceEffectiveDateFieldSpecified;

        private int statusIdField;

        private System.DateTime updateDateField;

        private bool updateDateFieldSpecified;

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long accountId
        {
            get
            {
                return this.accountIdField;
            }
            set
            {
                this.accountIdField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int chargeId
        {
            get
            {
                return this.chargeIdField;
            }
            set
            {
                this.chargeIdField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime createDate
        {
            get
            {
                return this.createDateField;
            }
            set
            {
                this.createDateField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool createDateSpecified
        {
            get
            {
                return this.createDateFieldSpecified;
            }
            set
            {
                this.createDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int currentCycleNumber
        {
            get
            {
                return this.currentCycleNumberField;
            }
            set
            {
                this.currentCycleNumberField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long customerChargeScheduleId
        {
            get
            {
                return this.customerChargeScheduleIdField;
            }
            set
            {
                this.customerChargeScheduleIdField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int customerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long customerProductId
        {
            get
            {
                return this.customerProductIdField;
            }
            set
            {
                this.customerProductIdField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime nextChargeDate
        {
            get
            {
                return this.nextChargeDateField;
            }
            set
            {
                this.nextChargeDateField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool nextChargeDateSpecified
        {
            get
            {
                return this.nextChargeDateFieldSpecified;
            }
            set
            {
                this.nextChargeDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int nextPeriodNumber
        {
            get
            {
                return this.nextPeriodNumberField;
            }
            set
            {
                this.nextPeriodNumberField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime priceEffectiveDate
        {
            get
            {
                return this.priceEffectiveDateField;
            }
            set
            {
                this.priceEffectiveDateField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool priceEffectiveDateSpecified
        {
            get
            {
                return this.priceEffectiveDateFieldSpecified;
            }
            set
            {
                this.priceEffectiveDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int statusId
        {
            get
            {
                return this.statusIdField;
            }
            set
            {
                this.statusIdField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime updateDate
        {
            get
            {
                return this.updateDateField;
            }
            set
            {
                this.updateDateField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool updateDateSpecified
        {
            get
            {
                return this.updateDateFieldSpecified;
            }
            set
            {
                this.updateDateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://apis.etak.com/")]
    public partial class customerChargeInfo
    {

        private long accountIdField;

        private double amountField;

        private System.DateTime chargeDateField;

        private bool chargeDateFieldSpecified;

        private int chargeIdField;

        private long customerChargeIdField;

        private long customerChargeScheduleIdField;

        private int customerIdField;

        private long customerProductIdField;

        private int cycleNumberField;

        private double informationalAmountField;

        private long invoiceIdField;

        private string iso4217CurrencyCodeField;

        private int periodNumberField;

        private double taxAmountField;

        private int taxIdField;

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long accountId
        {
            get
            {
                return this.accountIdField;
            }
            set
            {
                this.accountIdField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime chargeDate
        {
            get
            {
                return this.chargeDateField;
            }
            set
            {
                this.chargeDateField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore()]
        public bool chargeDateSpecified
        {
            get
            {
                return this.chargeDateFieldSpecified;
            }
            set
            {
                this.chargeDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int chargeId
        {
            get
            {
                return this.chargeIdField;
            }
            set
            {
                this.chargeIdField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long customerChargeId
        {
            get
            {
                return this.customerChargeIdField;
            }
            set
            {
                this.customerChargeIdField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long customerChargeScheduleId
        {
            get
            {
                return this.customerChargeScheduleIdField;
            }
            set
            {
                this.customerChargeScheduleIdField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int customerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long customerProductId
        {
            get
            {
                return this.customerProductIdField;
            }
            set
            {
                this.customerProductIdField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int cycleNumber
        {
            get
            {
                return this.cycleNumberField;
            }
            set
            {
                this.cycleNumberField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double informationalAmount
        {
            get
            {
                return this.informationalAmountField;
            }
            set
            {
                this.informationalAmountField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long invoiceId
        {
            get
            {
                return this.invoiceIdField;
            }
            set
            {
                this.invoiceIdField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string iso4217CurrencyCode
        {
            get
            {
                return this.iso4217CurrencyCodeField;
            }
            set
            {
                this.iso4217CurrencyCodeField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int periodNumber
        {
            get
            {
                return this.periodNumberField;
            }
            set
            {
                this.periodNumberField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double taxAmount
        {
            get
            {
                return this.taxAmountField;
            }
            set
            {
                this.taxAmountField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int taxId
        {
            get
            {
                return this.taxIdField;
            }
            set
            {
                this.taxIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [Serializable()]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [XmlType(Namespace = "http://apis.etak.com/")]
    public partial class chargingApplyResponse
    {

        private int codeField;

        private customerChargeInfo[] customerChargedResultListField;

        private string errorMsgField;

        private int flagField;

        private nextChargeScheduleInfo nextChargeScheduleInfoField;

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [XmlElement("customerChargedResultList", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public customerChargeInfo[] customerChargedResultList
        {
            get
            {
                return this.customerChargedResultListField;
            }
            set
            {
                this.customerChargedResultListField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string errorMsg
        {
            get
            {
                return this.errorMsgField;
            }
            set
            {
                this.errorMsgField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int flag
        {
            get
            {
                return this.flagField;
            }
            set
            {
                this.flagField = value;
            }
        }

        /// <remarks/>
        [XmlElement(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public nextChargeScheduleInfo nextChargeScheduleInfo
        {
            get
            {
                return this.nextChargeScheduleInfoField;
            }
            set
            {
                this.nextChargeScheduleInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    public delegate void firstPeriodChargingApplyCompletedEventHandler(object sender, firstPeriodChargingApplyCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    public partial class firstPeriodChargingApplyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal firstPeriodChargingApplyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public chargingApplyResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((chargingApplyResponse)(this.results[0]));
            }
        }
    }
}