using System;
using System.Runtime.Serialization;

namespace com.etak.core.model
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[DataContract]
    [Serializable]
    public class ImeiAssn
	{
		#region Private Members
		 
		private int _resourceid; 
		private string _imei;
        private DateTime? _startdate;
		#endregion
		
	
		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>		
        public virtual int Resourceid
		{
            get { return _resourceid; }
            set { _resourceid = value; }
		}


        public virtual string Imei
        {
            get { return _imei; }
            set { _imei = value; }
        }
			
		/// <summary>
		/// 
		/// </summary>		
        public virtual  DateTime? StartDate
        {
            get { return _startdate; }
            set { _startdate = value; }
        }



        #endregion Public Properties


    }
}
