using System;
using System.Runtime.Serialization;

namespace com.etak.core.model
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[DataContract]
	[Serializable]
	public class ImeiAssnHist
	{
		#region Private Members
		 
		private string _imei;
		private DateTime? _enddate;
	    private ImeiAssnHistPKInfo _PKInfo;

		#endregion
		
		#region Public Properties
			
		public virtual string Imei
		{
			get { return _imei; }
			set { _imei = value; }
		}
			
		public virtual DateTime? EndDate
		{
			get { return _enddate; }
			set { _enddate = value; }
		}

	    public virtual ImeiAssnHistPKInfo PKInfo
	    {
	        get { return _PKInfo; }
	        set { _PKInfo = value; }
	    }

	    #endregion Public Properties

		/// <summary>
		/// Override Equals method needed by Nhibernate to map the entity 
		/// </summary>
		/// <param name="obj"></param>
		/// <returns></returns>
		public override bool Equals(object obj)
		{
			if (this == obj) return true;

			var other = obj as ImeiAssnHist;
			if (other == null) return false;

			if (PKInfo.StartDate == other.PKInfo.StartDate && PKInfo.Resourceid == other.PKInfo.Resourceid) 
				return true;

			return false;
		}

		/// <summary>
		/// Override GetHashCode method needed by Nhibernate to map the entity
		/// </summary>
		/// <returns></returns>
		public override int GetHashCode()
		{
		    unchecked
		    {
		        int result = PKInfo.StartDate.GetHashCode();
                result = 29 * result + PKInfo.Resourceid.GetHashCode();

		        return result;
		    }
		}
	}

    [DataContract]
    [Serializable]
    public class ImeiAssnHistPKInfo
    {
        #region Fields

        private int _resourceid;
        private DateTime? _startDate = null;


        #endregion

        #region Attribute

        public int Resourceid
        {
            get { return _resourceid; }
            set { _resourceid = value; }
        }

        public DateTime? StartDate
        {
            get { return _startDate; }
            set { _startDate = value; }
        }
        #endregion

        /// <summary>
        /// Override Equals function needed by NHibernate to map the entity
        /// </summary>
        /// <param name="obj"></param>
        /// <returns></returns>
        public override bool Equals(object obj)
        {
            if (this == obj) return true;
            var other = obj as ImeiAssnHistPKInfo;
            if (other == null) return false;

            if (other.Resourceid == Resourceid && other.StartDate == StartDate)
            {
                return true;
            }

            return false;
        }

        /// <summary>
        /// Override GetHashCode needed for NHibernate to map the entity
        /// </summary>
        /// <returns></returns>
        public override int GetHashCode()
        {
            unchecked
            {
                int result = Resourceid.GetHashCode();
                result = 29*result + StartDate.GetHashCode();
                return result;
            }
        }
    }


}
