using System;
using System.Runtime.Serialization;

namespace com.etak.core.model
{
	/// <summary>
	///	Generated by MyGeneration using the NHibernate Object Mapping template
	/// </summary>
	[DataContract]
    [Serializable]
    public class LifecycleStatusTransitionNotification
	{

		#region Private Members
		private bool _isChanged;

		private long? _seqid; 
		private string _msisdn; 
		private int? _prestatus; 
		private int? _currentstatus; 
		private int _eventid; 
		private int _statusid;
        private int _mvnoID;
		private DateTime _createtime; 
		private DateTime? _updatetime; 		
		#endregion

		#region Default ( Empty ) Class Constuctor
		/// <summary>
		/// default constructor
		/// </summary>
		public LifecycleStatusTransitionNotification()
		{
			 
			 
		}
		#endregion // End of Default ( Empty ) Class Constuctor

		#region Required Fields Only Constructor
		/// <summary>
		/// required (not null) fields only constructor
		/// </summary>
        public LifecycleStatusTransitionNotification(
			long seqid, 
			string msisdn, 
			int prestatus, 
			int currentstatus, 
			int eventid, 
			int statusid, 
			DateTime createtime)
			: this()
		{
			_seqid = seqid;
			_msisdn = msisdn;
			_prestatus = prestatus;
			_currentstatus = currentstatus;
			_eventid = eventid;
			_statusid = statusid;
			_createtime = createtime;
			_updatetime = DateTime.MinValue;
		}
		#endregion // End Required Fields Only Constructor

		#region Public Properties
			
		/// <summary>
		/// 
		/// </summary>
		public long? Seqid
		{
			get { return _seqid; }
			set
			{
				_isChanged |= ( _seqid != value ); 
				_seqid = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public string Msisdn
		{
			get { return _msisdn; }

			set	
			{	
				 
				_isChanged |= (_msisdn != value); _msisdn = value;
			}
		}
			
		/// <summary>
		/// 
		/// </summary>
		public int? Prestatus
		{
			get { return _prestatus; }
			set
			{
				_isChanged |= ( _prestatus != value ); 
				_prestatus = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public int? Currentstatus
		{
			get { return _currentstatus; }
			set
			{
				_isChanged |= ( _currentstatus != value ); 
				_currentstatus = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public int Eventid
		{
			get { return _eventid; }
			set
			{
				_isChanged |= ( _eventid != value ); 
				_eventid = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public int Statusid
		{
			get { return _statusid; }
			set
			{
				_isChanged |= ( _statusid != value ); 
				_statusid = value;
			}

		}

        public int MVNOID
        {
            get { return _mvnoID; }
            set
            {
                _isChanged |= (_mvnoID != value);
                _mvnoID = value;
            }
        }
			
		/// <summary>
		/// 
		/// </summary>
		public DateTime Createtime
		{
			get { return _createtime; }
			set
			{
				_isChanged |= ( _createtime != value ); 
				_createtime = value;
			}

		}
			
		/// <summary>
		/// 
		/// </summary>
		public DateTime? Updatetime
		{
			get { return _updatetime; }
			set
			{
				_isChanged |= ( _updatetime != value ); 
				_updatetime = value;
			}

		}
			
		/// <summary>
		/// Returns whether or not the object has changed it's values.
		/// </summary>
		public bool IsChanged
		{
			get { return _isChanged; }
		}
				
		#endregion 
	}
}
